// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvmtdulvagqgzhngsoxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bXRkdWx2YWdxZ3pobmdzb3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzM4MDYsImV4cCI6MjA2MTA0OTgwNn0.giZitstglD6okNyXnN8_TUJEyiCCRAd-0HUkJRefOY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);